const IMAGES_INIT = 'IMAGES_INIT'
const CURRENT_KEY_SET = 'CURRENT_KEY_SET'
const LEFT_KEY_SET = 'LEFT_KEY_SET'
const RIGHT_KEY_SET = 'RIGHT_KEY_SET'


export default {
  IMAGES_INIT,
  CURRENT_KEY_SET,
  LEFT_KEY_SET,
  RIGHT_KEY_SET
}
